openapi: 3.0.1
info:
  title: API
  version: "1"
servers:
- url: http://localhost:3000/
security: []
tags: []

paths:
  /test:
    get:
      summary: Endpoint
      operationId: endpoint
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

components:
  schemas:
    Result:
      type: object
      required:
        - currentTime
        - identifier
        - theoreticalNextStops
      properties:
        currentTime:
          type: string
          format: date-time
        identifier:
          type: string
          format: uuid
        name:
          type: string
        nextStops:
          $ref: '#/components/schemas/RealTimeNextStops'
        theoreticalNextStops:
          $ref: '#/components/schemas/TheoreticalNextStops'

    RealTimeNextStops:
      type: array
      items:
        $ref: '#/components/schemas/RealTimeNextStop'

    RealTimeNextStop:
      type: object
      required:
        - directionName
        - destinationName
        - status
      properties:
        directionId:
          type: string
        directionName:
          type: string
        destinationName:
          type: string
        servicePatternName:
          type: string
        waitingTimeInMinutes:
          type: integer
        status:
          type: string
          enum:
          - AVAILABLE_WAITING_TIME
          - ATDOCK
          - APPROACHING
          - TRANSIT
          - UNAVAILABLE
          - LEAVING
          - UNKNOWN

    TheoreticalNextStops:
      type: array
      items:
        $ref: '#/components/schemas/TheoreticalNextStop'

    TheoreticalNextStop:
      type: object
      required:
        - directionName
        - destinationName
      properties:
        directionId:
          type: string
        directionName:
          type: string
        destinationName:
          type: string
        servicePatternName:
          type: string
        dateTime:
          description: Date and time of next stop.
          type: string
          format: date-time
        isLast:
          description: True if this stop is the last stop before end of service for this direction.
          type: boolean
        isFirst:
          description: True if this stop is the first stop before end of service for this direction.
          type: boolean
